#!/bin/sh
#
# Map ISP to ASN.
#
# 20190130  Kimmo Suominen
#

set -e
set -u

asn='
    blc=51935
    dna=16086
    elisa=719
    funet=1741
    globalwire=8145
    google=15169
    nebula=29422
    netplaza=20904
    noisystream=51311
    suomicom=16302
    telia=1759
'

case "${1}" in
LIST)
    echo "${asn}" \
    | sed \
	-e 's/  *//g' \
	-e 's/=.*$//' \
	-e '/^$/ d' \
    | sort
    ;;
SUMMARY)
    count="$("${0}" LIST | wc -l)"
    echo "${count} ${0##*/}"
    ;;
*)
    echo "${asn}" \
    | sed -n \
	-e 's/  *//g' \
	-e "/^${1}=/ {s///; p;}" \
    ;;
esac
